<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\WebA\WebA.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="bunit" Version="2.7.2" />
    <PackageReference Include="TUnit" Version="1.34.5" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
